### ISSUE TITLE
google cloud stage4

### ISSUE THREAD

**Issue by skunk73** [asarubbo/gentoo-stage4#1]
Hey!
wouldn't a gcloud compatible (hardened) stage4 be something awesome? :)
Guidelines may be found [here](https://cloud.google.com/compute/docs/images/configuring-imported-images).

**Comment by asarubbo** [comment]
Hello,

atm I don't have an account on google cloud. If you can provide one, I will do my best to make it working there.

**Comment by skunk73** [comment]
please give me your gmail account or please create one...

**Comment by skunk73** [comment]
oh btw, since all grsecurity kernel forks are dead, what about using [anthraxx's tree](https://github.com/anthraxx/linux-hardened) as a replacement for hardened-sources?

**Comment by asarubbo** [comment]
Unfortunately this can't be treat like a generic distro. Fox example...if we had a way to use grsecurity, I'm sure I wasn't able to put it into the stage4 just because you may want some modules enabled or some modules disabled and vice-versa.
So since this is Gentoo, you have a fast way to start, then you can start your customization.

My gmail account is name.surname@gmail.com

Thanks

**Comment by skunk73** [comment]
I understand... please check mail...

**Comment by asarubbo** [comment]
I don't have anything on my inbox..

**Comment by skunk73** [comment]
well, I've used literally the email you gave me... please check again...

**Comment by asarubbo** [comment]
I received the invite. However the console says that there are no billing account(s) associated

**Comment by skunk73** [comment]
please reach me over hangout when you've some time, thank you.

**Comment by asarubbo** [comment]
Just to keep the topic up-to-date for everyone that will read:

Install this stage4 on google cloud is possible using the generic script.
However for what I was able to see, google does not offer a rescue. Instead you need to create a new VM and attach the disk, so in order to install you need to do:

1) Create an empty disk
2) Install a new VM with a linux distro
3) Attach the disk
4) Make the installation on the attached disk

Note that the point 4 is already supported by changing the 'DISK' variable.
In order to works you need to have:
DISK="/dev/sdb"
ESP="/dev/sda1"
BOOT="/dev/sda2"
ROOT="/dev/sda3"

DISK will be used during the local install, so you are telling to your system to install into /dev/sdb disk, but in the configuration files it will use "/dev/sda*"

I will make a document to clarify those details.

See also: https://cloud.google.com/compute/docs/disks/add-persistent-disk#attachdiskrunninginstance
